### ISSUE TITLE
Kotlin extension

### ISSUE THREAD

**Issue by varunchandran333** [RohitSurwase/UCE-Handler#1]
`new UCEHandler.Builder(this).build();`  ---->>**In application class**

**_How can this be written in KOTLIN??_**

**Comment by RohitSurwase** [comment]
You can initialize it by-

`UCEHandler.Builder(applicationContext).build()`

Moreover, I would recommend you to activate activity-logs, and adding email address too. You can refer GitHub README for the same.
Like-

`UCEHandler.Builder(applicationContext)
.setTrackActivitiesEnabled(true)
.addCommaSeparatedEmailAddresses("comma separated email addresses")
.build()`

**Comment by RohitSurwase** [comment]
I am closing the issue considering it will resolve your problem.

**Comment by RohitSurwase** [comment]
``
